website1:
  port: 3000
  domain: website1.com
  url: https://www.website1.com/
  cookie: cookieSecretForWebsite1

website2:
  port: 3001
  domain: website2.com
  url: https://www.website2.com/
  cookie: cookieSecretForWebsite2
  
  